k8s_health_check:
  stage: test
  image: python:3.9
  variables:
    PREENV: "dev"  # Change to your target environment
  before_script:
    - pip install kubernetes requests tabulate reportlab
  script:
    - |
      if [ $PREENV = dev ]
      then
        
        # Setup kubectl and kubeconfig for dev environment
        curl -LO https://storage.googleapis.com/kubernetes-release/release/stable.txt
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(cat stable.txt)/bin/linux/amd64/kubectl
        chmod +x kubectl
        mv kubectl /usr/local/bin/
        
        # Use your existing username/password pattern
        USERNAME=$B01USERNAME
        PASSWORD=$B01PASSWORD
        
        # Configure kubectl with your credentials (adjust server URL as needed)
        kubectl config set-cluster k8s --server="https://your-k8s-server:6443" --insecure-skip-tls-verify=true
        kubectl config set-credentials dev-user --username="$USERNAME" --password="$PASSWORD"
        kubectl config set-context default --cluster=k8s --user=dev-user
        kubectl config use-context default
        
        # Run health check for dev namespace
        python k8s_health_check.py your-dev-namespace --output-format both --output-dir reports
        
      fi
  artifacts:
    reports:
      junit: reports/junit.xml
    paths:
      - reports/
    expire_in: 1 week
    when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: manual
