stages:
  - monitor

variables:
  KUBECTL_VERSION: "1.28.0"
  
# Development monitoring
monitor_development:
  image: python:3.9-slim
  stage: monitor
  before_script:
    # Install dependencies
    - apt-get update -qq && apt-get install -y -qq curl
    - pip3 install pyyaml
    
    # Install kubectl
    - curl -LO "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
    - chmod +x kubectl && mv kubectl /usr/local/bin/
    
    # Setup kubeconfig from your npeconfig file
    - mkdir -p ~/.kube
    - sed "s/_DEV_SERVER_URL/${DEV_K8S_SERVER_URL}/g; s/DEV_USERNAME/${DEV_K8S_USERNAME}/g; s/DEV_PASSWORD_/${DEV_K8S_PASSWORD}/g" npeconfig > ~/.kube/config
    
    # Test connection
    - kubectl cluster-info
    - echo "✅ Connected to DEVELOPMENT cluster"
    
    # Create monitoring output directory
    - mkdir -p monitoring-output
    - echo "📁 Created monitoring-output directory for artifacts"
  
  script:
    - echo "🚧 Monitoring DEVELOPMENT namespace..."
    - echo "🔍 Threshold set to ${DEV_THRESHOLD:-3} restarts"
    - python3 pod_restart_monitor.py --namespaces development --threshold ${DEV_THRESHOLD:-3}
    - echo "📊 Development monitoring completed"
    
    # Show what files were created
    - echo "📂 Generated files:"
    - ls -la monitoring-output/ || echo "No monitoring-output directory found"
  
  artifacts:
    when: always
    paths:
      - "monitoring-output/"
    expire_in: 1 week
  
  # Allow failure so pipeline doesn't stop if there are restart alerts
  allow_failure: true
  
  only:
    variables:
      - $MONITOR_DEVELOPMENT