variables:
  PREENV: "dev"

Monitor-B07:
  stage: monitor
  image: python:3.9
  variables:
    PREENV: "dev"
  before_script:
    # Install required system packages
    - apt-get update && apt-get install -y curl openssh-client sshpass coreutils gettext-base
    # Install Python packages
    - pip install kubernetes requests tabulate reportlab
  script:
    - |
      if [ $PREENV = dev ]
      then
        # Download and install kubectl
        KUBECTL_VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl
        
        # Set up authentication
        USERNAME=$B07USERNAME
        PASSWORD=$B07PASSWORD
        TOKEN=$(curl --insecure --user $USERNAME:$PASSWORD -X POST https://api.conductor.t-mobile.com/conductor/v1/auth/login)
        
        # Check if config file exists, if not create a template
        if [ ! -f "B07config-west" ]; then
          echo "Config file B07config-west not found. Creating template..."
          # You'll need to create this file or download it from somewhere
          # For now, creating a basic template
          cat > B07config-west << EOF
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://your-cluster-endpoint
    certificate-authority-data: YOUR_CA_DATA
  name: b07-prd-tfp-prd-w2
contexts:
- context:
    cluster: b07-prd-tfp-prd-w2
    user: =\$USERNAME=\$USERNAME=
  name: b07-prd-tfp-prd-w2
current-context: b07-prd-tfp-prd-w2
users:
- name: =\$USERNAME=\$USERNAME=
  user:
    token: =\$PASSWORD=\$PASSWORD=
EOF
        fi
        
        # Use pipe delimiter to avoid issues with special characters in variables
        sed -i "s|=\$USERNAME=\$USERNAME=|$USERNAME|g" B07config-west
        sed -i "s|=\$PASSWORD=\$PASSWORD=|$PASSWORD|g" B07config-west
        
        # Set the KUBECONFIG environment variable
        export KUBECONFIG=$PWD/B07config-west
        
        # Verify kubectl can connect
        kubectl cluster-info || echo "Warning: kubectl connection failed"
        
        echo "==========================Listing B07 Monitor=========================="
        
        python k8s_health_check.py b07-prd-tfp-prd-w2 --output-format html --output-dir reports
      else
        echo $USERNAME
      fi
  tags:
    - west-2
  artifacts:
    reports:
      junit: reports/junit.xml
    paths:
      - reports/
    expire_in: 1 week
    when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    when: manual
